# This is a basic workflow to help you get started with Actions

name: CI-CD-Pipline-to-AWS-ElasticBeastalk 
env: 
  EB_PACKAGE_S3_BUCKET_NAME: "daulet-flask-app-packages"
  EB_APPLICATION_NAME      : "Flaskapp"
  EB_ENVIRONMENT_NAME      : "Flaskapp-env"
  DEPLOY_PACKAGE_NAME      : "Flask_app_${{ github.sha }}.zip"
  AWS_REGION_NAME          : "us-east-1"
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]


jobs:
  
  my_ci_part:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Git clone our repo 
        uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Create ZIP deployment package
        run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./  -x *.git*
        
        
    
